# Generated by Django 5.2.8 on 2025-11-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Enter customer Name', max_length=20)),
                ('age', models.IntegerField(help_text='Enter age between 18 to 22')),
                ('address', models.CharField(help_text='Enter the Address', max_length=50)),
                ('mobile_no', models.IntegerField(help_text='Enter the Mobile Number')),
            ],
        ),
    ]
